# Generated by Django 5.1 on 2024-10-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventos',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='eventos')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=2000)),
                ('disponibilidad', models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
