# Generated by Django 5.1 on 2024-10-27 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='id_detalleDonacion',
        ),
        migrations.AddField(
            model_name='detalledonacion',
            name='id_donacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.donacion'),
        ),
    ]
